### ISSUE TITLE
Unify way to address configuration on backend

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea#165]
As a developer, I would like to see configuration in application.properties unified, I see the following:

```
security:
  provider: internal

appContext: http://localhost:5173
oidc.RoleClaim: realm_access.roles
cors.allowedOrigins: "http://localhost:5173,http://localhost:4173"

spring.security.rolePrefix: ff-
```

From this fast look, I would unify it in the following way:
```
security:
  provider: internal
  cors.allowedOrigins: "http://localhost:5173,http://localhost:4173"  
  oidc.RoleClaim: realm_access.roles
  rolePrefix: ff-

appContext: http://localhost:5173
```

In case rolePrefix is specific only for `oidc`, I would even move it to `security.oidc.rolePrefix: ff-`.

A/C:
- [x] unify the naming convention in application.properties file
- [x] modify configuration in deploy/keycloak-auth and deploy/internal-auth folder
- [x] modify configuration in 23ava-distribution
